language: android

jdk:
  - oraclejdk8

sudo: false

before_install:
  - chmod +x gradlew

android:
  components:
    - platform-tools
    - tools
    - build-tools-24.0.2
    #- android-18
    #- sys-img-armeabi-v7a-android-18
    #- android-19
    #- sys-img-armeabi-v7a-android-19
    #- android-21
    #- sys-img-armeabi-v7a-android-21
    #- android-22
    #- sys-img-armeabi-v7a-android-22
    #- android-23
    #- sys-img-armeabi-v7a-android-23
    - android-24
    - sys-img-armeabi-v7a-android-24
    - extra-google-m2repository
    - extra-android-m2repository

env:
   matrix:
      - ANDROID_TARGET=android-18
      - ANDROID_TARGET=android-19
      - ANDROID_TARGET=android-21
      - ANDROID_TARGET=android-22
      #- ANDROID_TARGET=android-23
      - ANDROID_TARGET=android-24

before_script:
    - echo no | android create avd --force -n test -t $ANDROID_TARGET  --abi armeabi-v7a
    - emulator -avd test -no-skin -no-audio -no-window &
    - android-wait-for-emulator
    - adb shell input keyevent 82 &

script:
    - android list target
    - ./gradlew build